name: 'Set all versions of a package'
description: 'Set all versions of a package'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2    

    - name: 'Set all versions of a package'
      shell: powershell
      run: |
        $json = (Get-Content "./manifest.json" -Raw) | ConvertFrom-Json
        ($json.packages) | foreach-object {  write "$($_.name.ToUpper())_VERSION=$($_.version)" >> $env:GITHUB_ENV}
