name: Build all

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # Tools
  package-diffutils:
    uses: ./.github/workflows/diffutils.yml
    concurrency:
      group: phase-one
      cancel-in-progress: true

  package-pkgconf:
    uses: ./.github/workflows/pkgconf.yml
    concurrency:
      group: tools
      cancel-in-progress: true

  package-meson:
    uses: ./.github/workflows/meson.yml
    concurrency:
      group: tools
      cancel-in-progress: true

  package-ninja:
    uses: ./.github/workflows/ninja.yml
    concurrency:
      group: tools
      cancel-in-progress: true

  package-winflexbison:
    uses: ./.github/workflows/winflexbison.yml
    concurrency:
      group: tools
      cancel-in-progress: true
