name: Build all

on:
  workflow_dispatch:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.ACTION_API_PAT }}

jobs:

  # Github can only have nesting of up to 20 actions in a single action
  # run. We'll need way more than that, as we have actions to get the 
  # version, setup the compiler, upload builds and far more. So, we need
  # to manually call other actions using the API to build everything.
  package-tools:
    runs-on: ubuntu-latest
    steps:
      - name: package-diffutils
        run: |
            curl -X POST -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" -d '{"ref":"main"}' \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/diffutils.yml/dispatches  

