name: Build all

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # Github can only have nesting of up to 20 actions in a single action
  # run. We'll need way more than that, as we have actions to get the 
  # version, setup the compiler, upload builds and far more. So, we need
  # to manually call other actions using the API to build everything.
  package-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: package-diffutils
        with:
          route: POST /repos/$GITHUB_REPOSITORY/actions/workflows/diffutils.yml/dispatches
          output: |
            ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_API_PAT }}

