name: set versions of packages

on:
  workflow_call:
    inputs:
      config-path:        
        required: true
        default: ./manifest.json
        type: string
    outputs:
      json_versions:
        description: "json versions"
        value: ${{ jobs.manifest.outputs.json_version }}

jobs:
  showenv:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
           echo ${{env.GITHUB_OUTPUT}}
  manifest:
    runs-on: windows-latest
    outputs:
      json_version: ${{steps.env.outputs.json}}      
    steps:     
      - name: Checkout code
        uses: actions/checkout@v2    

      - name: environment
        id: env
        shell: powershell
        run: |
          $json = (Get-Content ${{inputs.config-path}} -Raw) | ConvertFrom-Json
          write "json=$json" >> $env:GITHUB_OUTPUT
         
