name: set versions of packages

on:
  workflow_call:
    inputs:
      config-path:        
        required: true
        default: ./manifest.json
        type: string  

jobs:
  manifest:
    runs-on: windows-latest
      
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2    

      - name: environment
        id: env
        shell: powershell
        run: |
          $json = (Get-Content ${{inputs.config-path}} -Raw) | ConvertFrom-Json
          ($json.packages) | foreach-object {  write "$($_.name.ToUpper())_VERSION=$($_.version)" >> $env:GITHUB_OUTPUT}
      
      - name: show environment
        shell: powershell
        run:  $env:GITHUB_OUTPUT  
   
